name: scucourseplanner
services:
  - name: scucourseplannerdevelop
    github:
        branch: dev
        repo: CSEN-SCU/SCU-Course-Planner
        dockerfile_path: Dockerfile
  - name: scucourseplannermain
    github:
      branch: main
      repo: CSEN-SCU/SCU-Course-Planner
      dockerfile_path: Dockerfile