name: scucourseplannerdevelop
services:
  - name: scucourseplannerdevelop
    github:
      branch: develop
      repo: csen-scu/scu-course-planner
      dockerfile_path: Dockerfile

name: scucourseplannermain
services:
  - name: scucourseplannermain
    github:
      branch: main
      repo: csen-scu/scu-course-planner
      dockerfile_path: Dockerfile

name: scucourseplannerpr
services:
  - name: scucourseplannerpr
    github:
      branch: develop
      repo: csen-scu/scu-course-planner
      dockerfile_path: Dockerfile