name: scucourseplannerdevelop
services:
  - name: scucourseplannerdevelop
    envs:
      - key: SENTRY_AUTH_TOKEN
        value: ${SENTRY_AUTH_TOKEN}
        type: SECRET
    github:
      branch: develop
      repo: csen-scu/scu-course-planner
      dockerfile_path: Dockerfile

name: scucourseplannermain
services:
  - name: scucourseplannermain
    envs:
      - key: SENTRY_AUTH_TOKEN
        value: ${SENTRY_AUTH_TOKEN}
        type: SECRET
    github:
      branch: main
      repo: csen-scu/scu-course-planner
      dockerfile_path: Dockerfile

name: scucourseplannerpr
services:
  - name: scucourseplannerpr
    envs:
      - key: SENTRY_AUTH_TOKEN
        value: ${SENTRY_AUTH_TOKEN}
        type: SECRET
    github:
      branch: develop
      repo: csen-scu/scu-course-planner
      dockerfile_path: Dockerfile