name: scucourseplannerdevelop
services:
  - name: scucourseplannerdevelop
    envs:
      - key: SENTRY_AUTH_TOKEN
        value: ${SENTRY_AUTH_TOKEN}
        type: SECRET
    github:
      branch: develop
      repo: csen-scu/scu-course-planner
      dockerfile_path: Dockerfile

name: scucourseplannermain
services:
  - name: scucourseplannermain
    envs:
      - key: SENTRY_AUTH_TOKEN
        value: ${SENTRY_AUTH_TOKEN}
        type: SECRET
    github:
      branch: main
      repo: csen-scu/scu-course-planner
      dockerfile_path: Dockerfile

name: scucourseplannerpr
services:
  - name: scucourseplannerpr
    envs:
      - key: SENTRY_AUTH_TOKEN
        value: ${SENTRY_AUTH_TOKEN}
        type: SECRET
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        value: ${NEXT_PUBLIC_FIREBASE_API_KEY}
        type: SECRET
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        value: ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
        type: SECRET
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        value: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        type: SECRET
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        value: ${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
        type: SECRET
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        value: ${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
        type: SECRET
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        value: ${NEXT_PUBLIC_FIREBASE_APP_ID}
        type: SECRET
      - key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
        value: ${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
        type: SECRET
    github:
      branch: develop
      repo: csen-scu/scu-course-planner
      dockerfile_path: Dockerfile