name: Update Courses

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  pull_request: # Initial testing
    branches:
      - develop

jobs:
  update-courses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests firebase-admin sentry-sdk

      - name: Set environment variables
        run: |
          echo "DSN=${{ secrets.SENTRY_DSN }}" >> $GITHUB_ENV
          echo "COURSES_API_URL=${{ secrets.COURSES_API_URL }}" >> $GITHUB_ENV
          echo "SECTIONS_API_URL=${{ secrets.SECTIONS_API_URL }}" >> $GITHUB_ENV

      - name: Run script
        run: |
          python scripts/courseData.py